# Generated by Django 3.0.8 on 2020-07-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist_items',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
