# Generated by Django 3.0.8 on 2020-07-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_user_watchlist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist_items',
            field=models.CharField(max_length=10),
        ),
    ]
