# Generated by Django 3.0.8 on 2020-07-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_watchlist_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='list_id',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='id',
            field=models.IntegerField(primary_key='True', serialize=False),
        ),
    ]
