# Generated by Django 3.0.8 on 2020-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200706_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cprice',
            field=models.IntegerField(),
        ),
    ]
