# Generated by Django 3.0.8 on 2020-07-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200706_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='count',
        ),
        migrations.AddField(
            model_name='listing',
            name='sprice',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
