# Generated by Django 3.0.8 on 2020-07-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20200706_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('wom', 'Women'), ('ele', 'Electronics'), ('kit', 'Kitchen'), ('oth', 'Others')], default='oth', max_length=3),
        ),
    ]
